# Generated by Django 4.2.5 on 2023-12-07 10:23

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Người dùng",
                "db_table": "tb_user",
            },
        ),
        migrations.CreateModel(
            name="Characters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(choices=[("1", "1"), ("2", "2")], max_length=10),
                ),
                (
                    "appearance",
                    models.ImageField(
                        blank=True,
                        default="temp/avatar.png",
                        null=True,
                        upload_to="avatar",
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhân vật",
                "db_table": "tb_characters",
            },
        ),
        migrations.CreateModel(
            name="Gifted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(default="")),
                ("properties", models.JSONField()),
            ],
            options={
                "verbose_name": "Tiên thiên khí vận",
                "db_table": "tb_gifted",
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(default="")),
            ],
            options={
                "verbose_name": "Danh hiệu",
                "db_table": "tb_title",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.IntegerField(default=0)),
                (
                    "char1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Relationship_char1",
                        to="app_user.characters",
                    ),
                ),
                (
                    "char2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Relationship_char2",
                        to="app_user.characters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mối quan hệ",
                "db_table": "tb_relationship",
            },
        ),
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuoi", models.IntegerField(default=10, verbose_name="tuổi")),
                ("tuoi_tho", models.IntegerField(default=80, verbose_name="tuổi thọ")),
                ("tam_tinh", models.IntegerField(default=50, verbose_name="tâm tình")),
                ("suc_khoe", models.IntegerField(default=50, verbose_name="sức khỏe")),
                ("the_luc", models.IntegerField(default=10, verbose_name="thể lực")),
                ("linh_luc", models.IntegerField(default=0, verbose_name="linh lực")),
                ("niem_luc", models.IntegerField(default=0, verbose_name="niệm lực")),
                ("may_man", models.IntegerField(default=1, verbose_name="may mắn")),
                ("ngo_tinh", models.IntegerField(default=1, verbose_name="ngộ tính")),
                ("danh_vong", models.IntegerField(default=0, verbose_name="danh vọng")),
                ("mi_luc", models.IntegerField(default=1, verbose_name="mị lực")),
                (
                    "mau_huyet",
                    models.IntegerField(default=100, verbose_name="máu huyết"),
                ),
                (
                    "cong_kich",
                    models.IntegerField(default=10, verbose_name="công kích"),
                ),
                ("phong_ngu", models.IntegerField(default=1, verbose_name="phòng ngự")),
                ("toc_do", models.IntegerField(default=1, verbose_name="tốc độ")),
                (
                    "khang_cong",
                    models.IntegerField(default=1, verbose_name="kháng công"),
                ),
                (
                    "khang_linh",
                    models.IntegerField(default=1, verbose_name="kháng linh"),
                ),
                ("bao_kich", models.IntegerField(default=0, verbose_name="bạo kích")),
                ("khang_bao", models.IntegerField(default=0, verbose_name="kháng bạo")),
                ("ne_tranh", models.IntegerField(default=0, verbose_name="né tránh")),
                (
                    "hoa_linh_can",
                    models.IntegerField(default=1, verbose_name="hỏa linh căn"),
                ),
                (
                    "thuy_linh_can",
                    models.IntegerField(default=1, verbose_name="thủy linh căn"),
                ),
                (
                    "phong_linh_can",
                    models.IntegerField(default=1, verbose_name="phong linh căn"),
                ),
                (
                    "moc_linh_can",
                    models.IntegerField(default=1, verbose_name="moc linh căn"),
                ),
                (
                    "tho_linh_can",
                    models.IntegerField(default=1, verbose_name="thổ linh căn"),
                ),
                ("luyen_khi", models.IntegerField(default=0, verbose_name="luyện khí")),
                ("luyen_dan", models.IntegerField(default=0, verbose_name="luyện đan")),
                ("hoa_phu", models.IntegerField(default=0, verbose_name="họa phù")),
                ("duoc_lieu", models.IntegerField(default=0, verbose_name="dược liệu")),
                (
                    "khoang_san",
                    models.IntegerField(default=0, verbose_name="khoáng sản"),
                ),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Properties_characters",
                        to="app_user.characters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thuộc tính",
                "db_table": "tb_properties",
            },
        ),
        migrations.AddField(
            model_name="characters",
            name="gifted",
            field=models.ManyToManyField(
                blank=True, related_name="Characters_gifted", to="app_user.gifted"
            ),
        ),
        migrations.AddField(
            model_name="characters",
            name="title",
            field=models.ManyToManyField(
                blank=True, related_name="Characters_title", to="app_user.title"
            ),
        ),
        migrations.AddField(
            model_name="characters",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Characters_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
