# Generated by Django 4.2.5 on 2023-12-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0001_initial"),
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Bag_characters",
                        to="app_user.characters",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="Bag_item", to="app_item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Túi đồ",
                "db_table": "tb_bag",
            },
        ),
    ]
