# Generated by Django 4.2.5 on 2023-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0002_bag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bag",
            name="items",
        ),
        migrations.AddField(
            model_name="bag",
            name="items",
            field=models.JSONField(default={}),
        ),
    ]
