# Generated by Django 4.2.5 on 2023-12-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0006_alter_item_quality"),
        ("app_user", "0003_remove_bag_items_bag_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Money",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.IntegerField(default=0)),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Money_characters",
                        to="app_user.characters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linh thạch",
                "db_table": "tb_money",
            },
        ),
        migrations.CreateModel(
            name="Equipped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Equipped_characters",
                        to="app_user.characters",
                    ),
                ),
                (
                    "foot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Equipped_foot",
                        to="app_item.item",
                    ),
                ),
                (
                    "hand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Equipped_hand",
                        to="app_item.item",
                    ),
                ),
                (
                    "shirt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Equipped_shirt",
                        to="app_item.item",
                    ),
                ),
                (
                    "trousers",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Equipped_trousers",
                        to="app_item.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trang bị",
                "db_table": "tb_equipped",
            },
        ),
    ]
