# Generated by Django 4.1.3 on 2024-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_alter_properties_cong_kich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownpet',
            name='properties',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='OwnMaid',
        ),
    ]
