# Generated by Django 4.2.5 on 2023-12-28 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0005_characters_clan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characters",
            name="clan",
        ),
    ]
