# Generated by Django 4.2.5 on 2023-12-28 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0009_alter_item_quality_alter_item_type_and_more"),
        ("app_user", "0006_remove_characters_clan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Knowledge_char",
                        to="app_user.characters",
                    ),
                ),
                (
                    "menu",
                    models.ManyToManyField(
                        blank=True, related_name="Knowledge_menu", to="app_item.menu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiến thức",
                "db_table": "tb_knowledge",
            },
        ),
    ]
