# Generated by Django 5.0.4 on 2024-05-29 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_remove_money_merit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chat_receiver', to='app_user.characters')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chat_sender', to='app_user.characters')),
            ],
            options={
                'verbose_name': 'Truyền tin',
                'db_table': 'tb_chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
