# Generated by Django 4.2.5 on 2023-12-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0007_knowledge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("exp", models.IntegerField(default=0)),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Level_char",
                        to="app_user.characters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cảnh giới",
                "db_table": "tb_level",
            },
        ),
    ]
