# Generated by Django 4.2.5 on 2024-01-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0008_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="properties",
            name="linh_luc",
        ),
        migrations.RemoveField(
            model_name="properties",
            name="the_luc",
        ),
        migrations.AddField(
            model_name="properties",
            name="exp",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="properties",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Level",
        ),
    ]
