# Generated by Django 5.0.4 on 2024-05-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_chat_delete_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='toc_do',
        ),
        migrations.AddField(
            model_name='properties',
            name='chi_mang',
            field=models.IntegerField(default=0, verbose_name='chí mạng'),
        ),
        migrations.AddField(
            model_name='properties',
            name='hoi_phuc',
            field=models.IntegerField(default=0, verbose_name='hồi phục'),
        ),
        migrations.AddField(
            model_name='properties',
            name='hut_mau',
            field=models.IntegerField(default=0, verbose_name='hut_mau'),
        ),
        migrations.AddField(
            model_name='properties',
            name='luc_hoi_phuc',
            field=models.IntegerField(default=0, verbose_name='lực hồi phục'),
        ),
        migrations.AddField(
            model_name='properties',
            name='ne_tranh',
            field=models.IntegerField(default=0, verbose_name='né tránh'),
        ),
        migrations.AddField(
            model_name='properties',
            name='sat_thuong_chi_mang',
            field=models.IntegerField(default=0, verbose_name='sát thương chí mạng'),
        ),
    ]
