# Generated by Django 4.2.5 on 2024-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_user",
            "0009_remove_properties_linh_luc_remove_properties_the_luc_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="sat_khi",
            field=models.IntegerField(default=0, verbose_name="sát khí"),
        ),
    ]
