# Generated by Django 5.0.4 on 2024-05-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_remove_properties_toc_do_properties_chi_mang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='phan_kich',
            field=models.IntegerField(default=0, verbose_name='phản kích'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='hut_mau',
            field=models.IntegerField(default=0, verbose_name='hút máu'),
        ),
    ]
