# Generated by Django 4.2.5 on 2024-01-01 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0010_properties_sat_khi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="properties",
            old_name="level",
            new_name="canh_gioi",
        ),
        migrations.RenameField(
            model_name="properties",
            old_name="exp",
            new_name="linh_luc",
        ),
    ]
