# Generated by Django 4.2.5 on 2024-01-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0011_rename_level_properties_canh_gioi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="linh_luc_yeu_cau",
            field=models.IntegerField(default=100),
        ),
    ]
