# Generated by Django 4.2.5 on 2024-01-02 03:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0012_properties_linh_luc_yeu_cau"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="date_join",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
