# Generated by Django 4.2.5 on 2024-01-02 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0015_book"),
        ("app_user", "0013_characters_date_join"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="loi_linh_can",
            field=models.IntegerField(default=1, verbose_name="lôi linh căn"),
        ),
        migrations.AlterField(
            model_name="properties",
            name="moc_linh_can",
            field=models.IntegerField(default=1, verbose_name="mộc linh căn"),
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ManyToManyField(
                        blank=True, related_name="Study_book", to="app_item.book"
                    ),
                ),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Study_characters",
                        to="app_user.characters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Công pháp lĩnh ngộ",
                "db_table": "tb_study",
            },
        ),
    ]
