# Generated by Django 4.2.5 on 2024-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0014_properties_loi_linh_can_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bag",
            name="books",
            field=models.JSONField(default=dict),
        ),
    ]
