# Generated by Django 3.2.4 on 2024-01-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0015_bag_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='dedication',
            field=models.IntegerField(default=0),
        ),
    ]
