# Generated by Django 4.1.3 on 2024-03-17 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descripstion', models.TextField(default='')),
                ('level', models.IntegerField(default=1)),
                ('quality', models.IntegerField(default=1)),
                ('attribute', models.CharField(choices=[('1', 'Hỏa'), ('2', 'Thủy'), ('3', 'Thổ'), ('4', 'Mộc'), ('5', 'Kim')], default='1', max_length=10)),
                ('properties', models.JSONField(default=dict)),
                ('price', models.IntegerField(default=1)),
                ('duration', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Công pháp',
                'db_table': 'tb_book',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descripstion', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='temp/item.jpg', null=True, upload_to='item')),
                ('type', models.CharField(choices=[('1', 'Trang bị tay'), ('2', 'Trang bị đầu'), ('3', 'Trang bị áo'), ('4', 'Trang bị quần'), ('5', 'Vật phẩm tiêu hao'), ('6', 'Nguyên liệu luyện chế'), ('7', 'Nguyên liệu lĩnh ngộ'), ('8', 'Nguyên liệu nâng cấp'), ('9', 'Vật phẩm thân mật'), ('10', 'Vật phẩm chúc phúc')], default='1', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('properties', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Vật phẩm',
                'db_table': 'tb_item',
            },
        ),
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descripstion', models.TextField(default='')),
                ('quality', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Người hầu',
                'db_table': 'tb_maid',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descripstion', models.TextField(default='')),
                ('quality', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Sủng vật',
                'db_table': 'tb_pet',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descripstion', models.TextField(default='')),
                ('type', models.CharField(choices=[('1', 'luyện khí'), ('2', 'luyện đan')], default='1', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menu_item', to='app_item.item')),
                ('materials', models.ManyToManyField(blank=True, related_name='Menu_materials', to='app_item.item')),
            ],
            options={
                'verbose_name': 'Công thức',
                'db_table': 'tb_menu',
            },
        ),
    ]
