# Generated by Django 4.2.5 on 2023-12-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("descripstion", models.TextField(default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="temp/item.jpg", null=True, upload_to="item"
                    ),
                ),
                ("properties", models.JSONField()),
            ],
        ),
    ]
