# Generated by Django 4.2.5 on 2023-12-26 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Đồ vật"},
        ),
        migrations.AlterModelTable(
            name="item",
            table="tb_item",
        ),
    ]
