# Generated by Django 4.1.3 on 2024-03-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='temp/item.jpg', null=True, upload_to='book'),
        ),
    ]
