# Generated by Django 4.2.5 on 2023-12-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0002_alter_item_options_alter_item_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3")], default="1", max_length=10
            ),
        ),
    ]
