# Generated by Django 4.1.3 on 2024-03-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='attribute',
        ),
    ]
