# Generated by Django 4.2.5 on 2023-12-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0003_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
