# Generated by Django 4.2.5 on 2023-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0004_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quality",
            field=models.IntegerField(default=1),
        ),
    ]
