# Generated by Django 4.2.5 on 2023-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0005_item_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quality",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3")], default="1", max_length=10
            ),
        ),
    ]
