# Generated by Django 4.2.5 on 2023-12-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0006_alter_item_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quality",
            field=models.CharField(
                choices=[
                    ("1", "equip hand"),
                    ("2", "equip foot"),
                    ("3", "equip shirt"),
                    ("4", "equip trousers"),
                    ("5", "food"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "equip hand"),
                    ("2", "equip foot"),
                    ("3", "equip shirt"),
                    ("4", "equip trousers"),
                    ("5", "food"),
                ],
                default="1",
                max_length=10,
            ),
        ),
    ]
