# Generated by Django 4.2.5 on 2023-12-28 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0007_alter_item_quality_alter_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quality",
            field=models.CharField(
                choices=[
                    ("1", "equip hand"),
                    ("2", "equip foot"),
                    ("3", "equip shirt"),
                    ("4", "equip trousers"),
                    ("5", "food"),
                    ("6", "material1"),
                    ("6", "material2"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "equip hand"),
                    ("2", "equip foot"),
                    ("3", "equip shirt"),
                    ("4", "equip trousers"),
                    ("5", "food"),
                    ("6", "material1"),
                    ("6", "material2"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("descripstion", models.TextField(default="")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Menu_item",
                        to="app_item.item",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(
                        related_name="Menu_materials", to="app_item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Công thức",
                "db_table": "tb_menu",
            },
        ),
    ]
