# Generated by Django 4.2.5 on 2023-12-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0008_alter_item_quality_alter_item_type_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quality",
            field=models.CharField(
                choices=[
                    ("1", "equip hand"),
                    ("2", "equip foot"),
                    ("3", "equip shirt"),
                    ("4", "equip trousers"),
                    ("5", "food"),
                    ("6", "material1"),
                    ("7", "material2"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "equip hand"),
                    ("2", "equip foot"),
                    ("3", "equip shirt"),
                    ("4", "equip trousers"),
                    ("5", "food"),
                    ("6", "material1"),
                    ("7", "material2"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="materials",
            field=models.ManyToManyField(
                blank=True, related_name="Menu_materials", to="app_item.item"
            ),
        ),
    ]
