# Generated by Django 4.2.5 on 2024-01-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0012_alter_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "Trang bị tay"),
                    ("2", "Trang bị chân"),
                    ("3", "Trang bị áo"),
                    ("4", "Trang bị quần"),
                    ("5", "Vật phẩm tiêu hao"),
                    ("6", "Nguyên liệu luyện đan"),
                    ("7", "Nguyên liệu luyện khí"),
                    ("8", "Vật phẩm chúc phúc"),
                ],
                default="1",
                max_length=10,
            ),
        ),
    ]
