# Generated by Django 4.2.5 on 2024-01-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0013_alter_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="type",
            field=models.CharField(
                choices=[("1", "luyện khí"), ("2", "luyện đan"), ("3", "họa phù")],
                default="1",
                max_length=10,
            ),
        ),
    ]
