# Generated by Django 4.2.5 on 2024-01-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0014_alter_menu_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("descripstion", models.TextField(default="")),
                ("level", models.IntegerField(default=1)),
                (
                    "attribute",
                    models.CharField(
                        choices=[
                            ("1", "Hỏa"),
                            ("2", "Thủy"),
                            ("3", "Thổ"),
                            ("4", "Mộc"),
                            ("5", "Phong"),
                            ("6", "Lôi"),
                        ],
                        default="1",
                        max_length=10,
                    ),
                ),
                ("properties", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Công pháp",
                "db_table": "tb_book",
            },
        ),
    ]
