# Generated by Django 4.2.5 on 2024-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0015_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.IntegerField(default=1),
        ),
    ]
