# Generated by Django 3.2.4 on 2024-01-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0016_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
