# Generated by Django 3.2.4 on 2024-01-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0017_alter_item_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
