# Generated by Django 4.1.3 on 2024-03-17 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('member', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Môn phái',
                'db_table': 'tb_clan',
            },
        ),
        migrations.CreateModel(
            name='ClanPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Chức vị môn phái',
                'db_table': 'tb_clan_position',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('member', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Thế lực',
                'db_table': 'tb_organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Chức vị thế lực',
                'db_table': 'tb_organization_position',
            },
        ),
        migrations.CreateModel(
            name='RequestClan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Yêu cầu gia nhập môn phái',
                'db_table': 'tb_request_clan',
            },
        ),
        migrations.CreateModel(
            name='RequestOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Yêu cầu gia nhập thế lực',
                'db_table': 'tb_request_organization',
            },
        ),
    ]
