# Generated by Django 4.2.5 on 2023-12-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("member", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Môn phái",
                "db_table": "tb_clan",
            },
        ),
    ]
