# Generated by Django 4.1.3 on 2024-03-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clan', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorganization',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrganization_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='requestorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestOrganization_organization', to='app_clan.organization'),
        ),
        migrations.AddField(
            model_name='requestclan',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestClan_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='requestclan',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestClan_clan', to='app_clan.clan'),
        ),
        migrations.AddField(
            model_name='organizationposition',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationPosition_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='organizationposition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationPosition_organization', to='app_clan.organization'),
        ),
        migrations.AddField(
            model_name='clanposition',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClanPosition_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='clanposition',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClanPosition_clan', to='app_clan.clan'),
        ),
        migrations.AddField(
            model_name='clan',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clan_leader', to='app_user.characters'),
        ),
    ]
