# Generated by Django 4.2.5 on 2023-12-28 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0006_remove_characters_clan"),
        ("app_clan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clan",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Clan_leader",
                to="app_user.characters",
            ),
        ),
        migrations.RemoveField(
            model_name="clan",
            name="member",
        ),
        migrations.AddField(
            model_name="clan",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="Clan_member", to="app_user.characters"
            ),
        ),
    ]
