# Generated by Django 4.1.3 on 2024-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clan', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='level',
        ),
        migrations.AlterField(
            model_name='organization',
            name='member',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RequestOrganization',
        ),
    ]
