# Generated by Django 4.2.5 on 2023-12-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_clan",
            "0003_remove_clan_leader_remove_clan_member_clanposition_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clan",
            name="member",
            field=models.IntegerField(default=1),
        ),
    ]
