# Generated by Django 3.2.4 on 2024-01-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clan', '0005_requestclan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clan',
            name='exp_request',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='clan',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
