# Generated by Django 5.0.4 on 2024-05-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clan', '0005_alter_clan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='notification',
            field=models.TextField(default=''),
        ),
    ]
