# Generated by Django 5.0.4 on 2024-05-24 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clan', '0006_clan_notification'),
        ('app_user', '0006_ownpet_properties_delete_ownmaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('defender', models.IntegerField(default=1000)),
                ('power', models.IntegerField(default=100)),
                ('resources', models.IntegerField(default=100)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locality_char', to='app_user.characters')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Locality_organization', to='app_clan.organization')),
            ],
            options={
                'verbose_name': 'Địa bàn',
                'db_table': 'tb_locality',
            },
        ),
        migrations.DeleteModel(
            name='OrganizationPosition',
        ),
    ]
