# Generated by Django 3.2.4 on 2024-01-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clan', '0006_auto_20240102_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanposition',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
