# Generated by Django 3.2.4 on 2024-01-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_money_dedication'),
        ('app_clan', '0007_alter_clanposition_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ManyToManyField(blank=True, related_name='OnlineClan_char', to='app_user.Characters')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OnlineClan_clan', to='app_clan.clan')),
            ],
            options={
                'verbose_name': 'Thành viên môn phái có mặt',
                'db_table': 'tb_online_clan',
            },
        ),
    ]
