# Generated by Django 5.0.4 on 2024-05-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clan', '0011_alter_locality_char'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
