# Generated by Django 3.2.4 on 2024-01-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=1)),
                ('quality', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Thành trì',
                'db_table': 'tb_city',
            },
        ),
    ]
