# Generated by Django 4.1.3 on 2024-03-17 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('member', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bảng',
                'db_table': 'tb_board',
            },
        ),
        migrations.CreateModel(
            name='BoardChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bảng khiêu chiến',
                'db_table': 'tb_board_challenge',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=1)),
                ('quality', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Thành trì',
                'db_table': 'tb_city',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('prize', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Kỳ ngộ',
                'db_table': 'tb_event',
            },
        ),
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=1)),
                ('quality', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tháp',
                'db_table': 'tb_tower',
            },
        ),
        migrations.CreateModel(
            name='TowerChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('floor', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tháp khiêu chiến',
                'db_table': 'tb_tower_challenge',
            },
        ),
    ]
