# Generated by Django 3.2.4 on 2024-01-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_money_dedication'),
        ('app_location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ManyToManyField(blank=True, related_name='OnlineCity_char', to='app_user.Characters')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OnlineCity_clan', to='app_location.city')),
            ],
            options={
                'verbose_name': 'Người nhập thành',
                'db_table': 'tb_online_city',
            },
        ),
    ]
