# Generated by Django 4.1.3 on 2024-03-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_location', '0001_initial'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerchallenge',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TowerChallenge_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='towerchallenge',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TowerChallenge_tower', to='app_location.tower'),
        ),
        migrations.AddField(
            model_name='event',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='Event_member', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='boardchallenge',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoardChallenge_board', to='app_location.board'),
        ),
        migrations.AddField(
            model_name='boardchallenge',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoardChallenge_char', to='app_user.characters'),
        ),
    ]
