# Generated by Django 4.1.3 on 2024-03-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardchallenge',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardchallenge',
            name='char',
        ),
        migrations.RemoveField(
            model_name='event',
            name='member',
        ),
        migrations.RemoveField(
            model_name='towerchallenge',
            name='char',
        ),
        migrations.RemoveField(
            model_name='towerchallenge',
            name='tower',
        ),
        migrations.RemoveField(
            model_name='city',
            name='price',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardChallenge',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Tower',
        ),
        migrations.DeleteModel(
            name='TowerChallenge',
        ),
    ]
