# Generated by Django 3.2.4 on 2024-01-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_money_dedication'),
        ('app_location', '0002_onlinecity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=1)),
                ('quality', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tháp',
                'db_table': 'tb_tower',
            },
        ),
        migrations.CreateModel(
            name='TowerChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=1)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TowerChallenge_char', to='app_user.characters')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TowerChallenge_tower', to='app_location.tower')),
            ],
            options={
                'verbose_name': 'Tháp khiêu chiến',
                'db_table': 'tb_tower_challenge',
            },
        ),
    ]
