# Generated by Django 4.1.3 on 2024-03-22 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_remove_properties_hoa_thuoc_tinh_and_more'),
        ('app_location', '0003_remove_boardchallenge_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('floor', models.IntegerField(default=0)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TowerChallenge_char', to='app_user.characters')),
            ],
            options={
                'verbose_name': 'Tháp khiêu chiến',
                'db_table': 'tb_tower',
            },
        ),
    ]
