# Generated by Django 3.2.4 on 2024-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0003_tower_towerchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerchallenge',
            name='floor',
            field=models.IntegerField(default=0),
        ),
    ]
