# Generated by Django 3.2.4 on 2024-01-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0004_alter_towerchallenge_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('rank', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Bảng khiêu chiến',
                'db_table': 'tb_challenge_board',
            },
        ),
    ]
