# Generated by Django 4.1.3 on 2024-03-30 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_money_merit'),
        ('app_location', '0004_tower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField()),
                ('question', models.TextField()),
                ('answer_1', models.TextField()),
                ('answer_2', models.TextField()),
                ('answer_3', models.TextField()),
            ],
            options={
                'verbose_name': 'Danh sách câu hỏi',
                'db_table': 'tb_question',
            },
        ),
        migrations.CreateModel(
            name='QuestionChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuestionChar_char', to='app_location.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuestionChar_question', to='app_user.characters')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'db_table': 'tb_question_char',
            },
        ),
    ]
