# Generated by Django 4.1.3 on 2024-03-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0006_alter_questionchar_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_correct',
            field=models.IntegerField(default=1),
        ),
    ]
