# Generated by Django 4.1.3 on 2024-03-30 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_money_merit'),
        ('app_location', '0007_question_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchar',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuestionChar_char', to='app_user.characters'),
        ),
    ]
