# Generated by Django 4.2.5 on 2023-12-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_item", "0012_alter_item_type"),
        ("app_user", "0007_knowledge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gardent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My gardent", max_length=100)),
                ("level", models.IntegerField(default=1)),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Gardent_char",
                        to="app_user.characters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vườn cây",
                "db_table": "tb_gardent",
            },
        ),
        migrations.CreateModel(
            name="Seed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                ("time", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Hạt giống",
                "db_table": "tb_seed",
            },
        ),
        migrations.CreateModel(
            name="GardentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "gardent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="GardentSlot_gardent",
                        to="app_job.gardent",
                    ),
                ),
                (
                    "seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="GardentSlot_plant",
                        to="app_job.seed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chậu cây",
                "db_table": "tb_gardentslot",
            },
        ),
    ]
