# Generated by Django 4.1.3 on 2024-03-17 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='My cage', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Chuồng thú',
                'db_table': 'tb_cage',
            },
        ),
        migrations.CreateModel(
            name='CageSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Lồng',
                'db_table': 'tb_cage_slot',
            },
        ),
        migrations.CreateModel(
            name='Gardent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='My gardent', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Vườn cây',
                'db_table': 'tb_gardent',
            },
        ),
        migrations.CreateModel(
            name='GardentSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Chậu cây',
                'db_table': 'tb_gardent_slot',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='My house', max_length=100)),
                ('quality', models.IntegerField(default=1)),
                ('store', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Động phủ',
                'db_table': 'tb_house',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='My kitchen', max_length=100)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Phòng luyện đan',
                'db_table': 'tb_kitchen',
            },
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='My lake', max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Hồ nước',
                'db_table': 'tb_lake',
            },
        ),
        migrations.CreateModel(
            name='LakeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Lượng cá',
                'db_table': 'tb_lake_slot',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='temp/item.jpg', null=True, upload_to='seed')),
                ('time', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Hạt giống',
                'db_table': 'tb_seed',
            },
        ),
        migrations.CreateModel(
            name='Smithy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='My smithy', max_length=100)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Phòng luyện khí',
                'db_table': 'tb_smithy',
            },
        ),
    ]
