# Generated by Django 4.1.3 on 2024-03-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        ('app_item', '0001_initial'),
        ('app_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smithy',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Smithy_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='seed',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seed_item', to='app_item.item'),
        ),
        migrations.AddField(
            model_name='lakeslot',
            name='lake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LakeSlot_lake', to='app_job.lake'),
        ),
        migrations.AddField(
            model_name='lakeslot',
            name='seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LakeSlot_seed', to='app_job.seed'),
        ),
        migrations.AddField(
            model_name='lake',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lake_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kitchen_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='house',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='House_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='gardentslot',
            name='gardent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GardentSlot_gardent', to='app_job.gardent'),
        ),
        migrations.AddField(
            model_name='gardentslot',
            name='seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GardentSlot_seed', to='app_job.seed'),
        ),
        migrations.AddField(
            model_name='gardent',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gardent_char', to='app_user.characters'),
        ),
        migrations.AddField(
            model_name='cageslot',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CageSlot_cage', to='app_job.cage'),
        ),
        migrations.AddField(
            model_name='cageslot',
            name='seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CageSlot_seed', to='app_job.seed'),
        ),
        migrations.AddField(
            model_name='cage',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cage_char', to='app_user.characters'),
        ),
    ]
