# Generated by Django 4.2.5 on 2023-12-28 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_user", "0007_knowledge"),
        ("app_job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="My storehouse", max_length=100)),
                ("seed", models.JSONField(default=dict)),
                (
                    "char",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="StoreHouse_char",
                        to="app_user.characters",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhà kho",
                "db_table": "tb_storehouse",
            },
        ),
    ]
