# Generated by Django 4.1.3 on 2024-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='type',
            field=models.CharField(choices=[('1', 'linh thảo'), ('2', 'linh thú'), ('3', 'linh ngư')], default='1', max_length=10),
        ),
    ]
