# Generated by Django 4.2.5 on 2023-12-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_item", "0012_alter_item_type"),
        ("app_job", "0002_storehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="seed",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Seed_item",
                to="app_item.item",
            ),
        ),
    ]
