# Generated by Django 4.1.3 on 2024-03-22 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_studyprocess_id'),
        ('app_job', '0003_seed_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oven_char', to='app_user.characters')),
            ],
            options={
                'verbose_name': 'Đan lô',
                'db_table': 'tb_oven',
            },
        ),
        migrations.RemoveField(
            model_name='smithy',
            name='char',
        ),
        migrations.DeleteModel(
            name='Kitchen',
        ),
        migrations.DeleteModel(
            name='Smithy',
        ),
    ]
