# Generated by Django 4.2.5 on 2023-12-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_job", "0003_seed_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="gardentslot",
            name="price",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="seed",
            name="price",
            field=models.IntegerField(default=1),
        ),
    ]
