# Generated by Django 4.2.5 on 2023-12-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_job", "0004_gardentslot_price_seed_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="gardent",
            name="exp",
            field=models.IntegerField(default=0),
        ),
    ]
