# Generated by Django 4.2.5 on 2023-12-29 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_job", "0006_remove_gardentslot_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gardentslot",
            name="seed",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="GardentSlot_plant",
                to="app_job.seed",
            ),
        ),
        migrations.AlterField(
            model_name="gardentslot",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
