# Generated by Django 4.2.5 on 2023-12-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_job", "0007_alter_gardentslot_seed_alter_gardentslot_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gardentslot",
            name="start_time",
        ),
        migrations.AddField(
            model_name="gardentslot",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
    ]
