# Generated by Django 4.2.5 on 2023-12-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_job", "0010_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("level", models.IntegerField()),
            ],
            options={
                "verbose_name": "Mỏ quặng",
                "db_table": "tb_mines",
            },
        ),
    ]
