# Generated by Django 4.2.5 on 2023-12-29 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_job", "0011_mines"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mines",
            options={"ordering": ["-quantity"], "verbose_name": "Mỏ quặng"},
        ),
    ]
