# Generated by Django 4.2.5 on 2024-01-01 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_job", "0013_alter_mines_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mines",
            options={"ordering": ["level"], "verbose_name": "Mỏ quặng"},
        ),
    ]
