# Generated by Django 3.2.4 on 2024-01-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0014_alter_mines_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardent',
            name='quality',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
