# Generated by Django 5.0.4 on 2024-05-24 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0006_ownpet_properties_delete_ownmaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='temp/item.jpg', null=True, upload_to='organization')),
                ('member', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Thế lực',
                'db_table': 'tb_organization',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('defender', models.IntegerField(default=1000)),
                ('power', models.IntegerField(default=100)),
                ('resources', models.IntegerField(default=100)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locality_char', to='app_user.characters', unique=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Locality_organization', to='app_organization.organization')),
            ],
            options={
                'verbose_name': 'Địa bàn',
                'db_table': 'tb_locality',
            },
        ),
    ]
