# Generated by Django 5.0.4 on 2024-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0003_alter_locality_power_alter_mine_defender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='get_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='market',
            name='limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mine',
            name='get_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mine',
            name='limit',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='market',
            name='store',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mine',
            name='store',
            field=models.IntegerField(default=0),
        ),
    ]
