# Generated by Django 5.0.4 on 2024-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0004_market_get_at_market_limit_mine_get_at_mine_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='time_protect',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='time_protect',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mine',
            name='time_protect',
            field=models.DateTimeField(null=True),
        ),
    ]
