# Generated by Django 5.0.4 on 2024-05-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0005_locality_time_protect_market_time_protect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='defender',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='market',
            name='defender',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='market',
            name='limit',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='market',
            name='produce',
            field=models.IntegerField(default=3),
        ),
    ]
