# Generated by Django 5.0.4 on 2024-05-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0006_alter_locality_defender_alter_market_defender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='get_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mine',
            name='get_at',
            field=models.DateTimeField(null=True),
        ),
    ]
