# Generated by Django 5.0.4 on 2024-05-25 04:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0007_alter_market_get_at_alter_mine_get_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mail_receiver', to='app_organization.locality')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mail_sender', to='app_organization.locality')),
            ],
            options={
                'verbose_name': 'Thư thế lực',
                'db_table': 'tb_mail',
                'ordering': ['-created_at'],
            },
        ),
    ]
